# TITLE OF YOUR SITE
title: Bram Vandenbussche

image_url: 

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
baseurl: /

# Default Markdown Engine
markdown: kramdown

# google_analytics: G-